<h1 align="center">Física Computacional.</h1>
<h1 align="center">Semestre 2026-1</h1>

<h2>Sergio A. Alcalá Corona </h2> 

---
### Joel Gómez Uribe
### Rodrigo Vega Vilchis
---

<h1 align="center">Programación para la física computacional</h1> 

## 1.1.4 Entrada y Salida de datos.

---
$\;$
## ENTRADA


### Obtener datos desde el usuario

Como ya hemos visto en algunos ejemplos, se puede pedir información del usuario y obtener datos insertados por el usuario directamente en la *linea de comandos* (donde se este interpretando `Python`), mediante el uso la función `input()` de la siguiente manera

In [5]:
x = input("Ingresa el valor de x: ")
print("El valor de x es" , x)

Ingresa el valor de x:  1


El valor de x es 1


In [6]:
a = float(input('Dame el valor de a: '))

print("El cuadrado de a es ", a*a)

Dame el valor de a:  2


El cuadrado de a es  4.0


In [7]:
temp = input("Ingresa el valor de la temperatura T: ")
T = float(temp)

print("El valor de T es" , T)

Ingresa el valor de la temperatura T:  3


El valor de T es 3.0


In [8]:
y = float(input("Ingresa el valor de y: "))
print("El valor de y es",y)

Ingresa el valor de y:  2


El valor de y es 2.0


Sin embargo, uno de los usos principales de Python para el cómputo científico es el de **procesar datos** generados en otro lado.

Por lo tanto, es necesario saber cómo importar y exportar archivos.

---

### Cargar arreglos desde un archivo de texto

Es posible tomar un conjunto de números guardados en un archivo de texto y convertirlos en un arreglo usando la biblioteca `loadtxt` de `numpy` de la siguiente manera:

In [9]:
import numpy as np

valores = np.loadtxt("valores.txt",float)
valores

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [10]:
valores = np.loadtxt("valores.txt",int)
valores

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

**Nota:** Solo funciona para archivos que contengan una sola linea, con valores separadaos ya sea por una coma o un tabulador.

Así entonces podriamos calcular su promedio (*aritmetico*):

In [11]:
promedio = sum(valores)/len(valores)
print(promedio)

8.0


o el promedio de los cuadrados:

In [12]:
promedio2 = sum(valores**2)/len(valores)
print(promedio2)

82.66666666666667


Pero también podemos calcular el promedio geometrico. 

Recordemos que el promedio geometrico de $n$ valores se define como:

### $ \displaystyle \overline{x} = \displaystyle \left[ \prod_{i = 1}^n x_i \right]^{\frac{1}{n}} $

Tomando el logaritmo natural a ambos lados, tenemos:

### $ \displaystyle \ln \overline{x} = \displaystyle \ln \left[ \prod_{i = 1}^n x_i \right]^{\frac{1}{n}} = \dfrac{1}{n} \sum_{i = 1}^n \ln x_i $

de tal manera que:

### $ \displaystyle \overline{x} = \displaystyle \exp \left( \dfrac{1}{n} \sum_{i = 1}^n \ln x_i \right)$

### **Ejercicio:** 

Ahora escribe un programa que realice la suma de los cuadrados de los valores tomados de un archivo de texto:

<h4 align="center">$\displaystyle s = \sum x^2 \; \; \; \forall x \in V_{txt}$</h4> 

In [13]:
N = 100
S = 0.0
x = np.loadtxt("valores.txt",int)

for k in range(1, N+1):
    S = S + x**2
    S += x**2
S

array([  200.,   800.,  1800.,  3200.,  5000.,  7200.,  9800., 12800.,
       16200., 20000., 24200., 28800., 33800., 39200., 45000.])

### **Ejercicio:** 


Escribe un programa que lea el archivo `valores.txt` y los guarde en una arreglo de `numpy`. Calcula el promedio geometrico de dichos datos

In [14]:
import math as mt

S = 0.0
n = 1

import numpy as np

x = np.loadtxt("valores.txt",int)

for i in range(1, n+1):
    S = (1/n) mt.ln x


SyntaxError: invalid syntax (652343645.py, line 11)

### Leer archivos

Para leer un archivo, primero es necesario abrirlo para leerse. Supongamos que tenemos un archivo llamado *datos.dat*, entonces lo podemos abrir para su lectura con:

In [158]:
entrada = open("datos.dat", "r")    # esto es un buffer

El segundo argumento, `"r"`, es para indicar que se va a leer (*“read”*) el archivo. 

El objeto `entrada` ahora representa el archivo.

Para leer del archivo abierto, hay varias posibilidades. 
Podemos leer todo de un golpe con `entrada.read()`, 

leer todo por líneas con `entrada.readlines()`, 

o línea por línea con `entrada.readline()`. 

Sin embargo, lo que se ha leído ya no se puede leer de nuevo sin cerrar el archivo con `entrada.close()` y volverlo a abrir.

Por ejemplo, podemos utilizar

In [146]:
entrada.readlines()

['0 \t 8 \n',
 '1 \t 23 \n',
 '2 \t 48 \n',
 '3 \t 83 \n',
 '4 \t 128 \n',
 '5 \t 183 \n',
 '6 \t 248 \n',
 '7 \t 323 \n',
 '8 \t 408 \n',
 '9 \t 503 \n',
 '10 \t 608 \n',
 '11 \t 723 \n',
 '12 \t 848 \n',
 '13 \t 983 \n',
 '14 \t 1128 \n',
 '15 \t 1283 \n',
 '16 \t 1448 \n',
 '17 \t 1623 \n',
 '18 \t 1808 \n',
 '19 \t 2003 \n',
 '20 \t 2208 \n',
 '21 \t 2423 \n',
 '22 \t 2648 \n',
 '23 \t 2883 \n',
 '24 \t 3128 \n',
 '25 \t 3383 \n',
 '26 \t 3648 \n',
 '27 \t 3923 \n',
 '28 \t 4208 \n',
 '29 \t 4503 \n',
 '30 \t 4808 \n',
 '31 \t 5123 \n',
 '32 \t 5448 \n',
 '33 \t 5783 \n',
 '34 \t 6128 \n',
 '35 \t 6483 \n',
 '36 \t 6848 \n',
 '37 \t 7223 \n',
 '38 \t 7608 \n',
 '39 \t 8003 \n',
 '40 \t 8408 \n',
 '41 \t 8823 \n',
 '42 \t 9248 \n',
 '43 \t 9683 \n',
 '44 \t 10128 \n',
 '45 \t 10583 \n',
 '46 \t 11048 \n',
 '47 \t 11523 \n',
 '48 \t 12008 \n',
 '49 \t 12503 \n',
 '50 \t 13008 \n',
 '51 \t 13523 \n',
 '52 \t 14048 \n',
 '53 \t 14583 \n',
 '54 \t 15128 \n',
 '55 \t 15683 \n',
 '56 \t 1

In [148]:
for linea in entrada.readlines():
    print(linea)

Sin embargo, tal vez la opción más fácil e intuitiva es:

In [149]:
for linea in entrada:
    print(linea)

Es decir, el archivo ¡se comporta como una secuencia!

Ahora bien, la línea viene como una sola cadena, con espacios etc. Para extraer la información, primero necesitamos dividirlo en palabras:

In [131]:
palabras = linea.split()

In [103]:
x = entrada.readlines()

In [104]:
x

['0 \t 8 \n',
 '1 \t 23 \n',
 '2 \t 48 \n',
 '3 \t 83 \n',
 '4 \t 128 \n',
 '5 \t 183 \n',
 '6 \t 248 \n',
 '7 \t 323 \n',
 '8 \t 408 \n',
 '9 \t 503 \n',
 '10 \t 608 \n',
 '11 \t 723 \n',
 '12 \t 848 \n',
 '13 \t 983 \n',
 '14 \t 1128 \n',
 '15 \t 1283 \n',
 '16 \t 1448 \n',
 '17 \t 1623 \n',
 '18 \t 1808 \n',
 '19 \t 2003 \n',
 '20 \t 2208 \n',
 '21 \t 2423 \n',
 '22 \t 2648 \n',
 '23 \t 2883 \n',
 '24 \t 3128 \n',
 '25 \t 3383 \n',
 '26 \t 3648 \n',
 '27 \t 3923 \n',
 '28 \t 4208 \n',
 '29 \t 4503 \n',
 '30 \t 4808 \n',
 '31 \t 5123 \n',
 '32 \t 5448 \n',
 '33 \t 5783 \n',
 '34 \t 6128 \n',
 '35 \t 6483 \n',
 '36 \t 6848 \n',
 '37 \t 7223 \n',
 '38 \t 7608 \n',
 '39 \t 8003 \n',
 '40 \t 8408 \n',
 '41 \t 8823 \n',
 '42 \t 9248 \n',
 '43 \t 9683 \n',
 '44 \t 10128 \n',
 '45 \t 10583 \n',
 '46 \t 11048 \n',
 '47 \t 11523 \n',
 '48 \t 12008 \n',
 '49 \t 12503 \n',
 '50 \t 13008 \n',
 '51 \t 13523 \n',
 '52 \t 14048 \n',
 '53 \t 14583 \n',
 '54 \t 15128 \n',
 '55 \t 15683 \n',
 '56 \t 1

Si todos los datos en realidad son números, entonces tenemos que procesar cada palabra, convirtiéndola en un número:

In [100]:
x = []

for i in palabras:
    #print(linea)
    #print(linea.split())
    M.append(linea.split())

In [101]:
np.array(x)

array([], dtype=float64)

## REINICIO A MI VERSION

In [159]:
entrada = open("datos.dat", "r")    # esto es un buffer

In [160]:
x = entrada.readlines()

In [161]:
x

['0 \t 8 \n',
 '1 \t 23 \n',
 '2 \t 48 \n',
 '3 \t 83 \n',
 '4 \t 128 \n',
 '5 \t 183 \n',
 '6 \t 248 \n',
 '7 \t 323 \n',
 '8 \t 408 \n',
 '9 \t 503 \n',
 '10 \t 608 \n',
 '11 \t 723 \n',
 '12 \t 848 \n',
 '13 \t 983 \n',
 '14 \t 1128 \n',
 '15 \t 1283 \n',
 '16 \t 1448 \n',
 '17 \t 1623 \n',
 '18 \t 1808 \n',
 '19 \t 2003 \n',
 '20 \t 2208 \n',
 '21 \t 2423 \n',
 '22 \t 2648 \n',
 '23 \t 2883 \n',
 '24 \t 3128 \n',
 '25 \t 3383 \n',
 '26 \t 3648 \n',
 '27 \t 3923 \n',
 '28 \t 4208 \n',
 '29 \t 4503 \n',
 '30 \t 4808 \n',
 '31 \t 5123 \n',
 '32 \t 5448 \n',
 '33 \t 5783 \n',
 '34 \t 6128 \n',
 '35 \t 6483 \n',
 '36 \t 6848 \n',
 '37 \t 7223 \n',
 '38 \t 7608 \n',
 '39 \t 8003 \n',
 '40 \t 8408 \n',
 '41 \t 8823 \n',
 '42 \t 9248 \n',
 '43 \t 9683 \n',
 '44 \t 10128 \n',
 '45 \t 10583 \n',
 '46 \t 11048 \n',
 '47 \t 11523 \n',
 '48 \t 12008 \n',
 '49 \t 12503 \n',
 '50 \t 13008 \n',
 '51 \t 13523 \n',
 '52 \t 14048 \n',
 '53 \t 14583 \n',
 '54 \t 15128 \n',
 '55 \t 15683 \n',
 '56 \t 1

In [162]:
entrada.close()

In [163]:
x = []
for i in x:
    palabras = x.split()
    numeros = []
    for palabra in palabras:
        x.append(numeros)

In [165]:
array_X = np.array(x)
print(array_X)

[]


## REINICIO A VERSION DEL PROFE

In [49]:
bote = open("datos.dat", "r")    # esto es un buffer
α = bote.readlines()

In [59]:
import numpy as np

bote.close()
α

['0 \t 8 \n',
 '1 \t 23 \n',
 '2 \t 48 \n',
 '3 \t 83 \n',
 '4 \t 128 \n',
 '5 \t 183 \n',
 '6 \t 248 \n',
 '7 \t 323 \n',
 '8 \t 408 \n',
 '9 \t 503 \n',
 '10 \t 608 \n',
 '11 \t 723 \n',
 '12 \t 848 \n',
 '13 \t 983 \n',
 '14 \t 1128 \n',
 '15 \t 1283 \n',
 '16 \t 1448 \n',
 '17 \t 1623 \n',
 '18 \t 1808 \n',
 '19 \t 2003 \n',
 '20 \t 2208 \n',
 '21 \t 2423 \n',
 '22 \t 2648 \n',
 '23 \t 2883 \n',
 '24 \t 3128 \n',
 '25 \t 3383 \n',
 '26 \t 3648 \n',
 '27 \t 3923 \n',
 '28 \t 4208 \n',
 '29 \t 4503 \n',
 '30 \t 4808 \n',
 '31 \t 5123 \n',
 '32 \t 5448 \n',
 '33 \t 5783 \n',
 '34 \t 6128 \n',
 '35 \t 6483 \n',
 '36 \t 6848 \n',
 '37 \t 7223 \n',
 '38 \t 7608 \n',
 '39 \t 8003 \n',
 '40 \t 8408 \n',
 '41 \t 8823 \n',
 '42 \t 9248 \n',
 '43 \t 9683 \n',
 '44 \t 10128 \n',
 '45 \t 10583 \n',
 '46 \t 11048 \n',
 '47 \t 11523 \n',
 '48 \t 12008 \n',
 '49 \t 12503 \n',
 '50 \t 13008 \n',
 '51 \t 13523 \n',
 '52 \t 14048 \n',
 '53 \t 14583 \n',
 '54 \t 15128 \n',
 '55 \t 15683 \n',
 '56 \t 1

In [60]:
β = [] 

for i in α:
    β.append(i.split())

In [61]:
β

[['0', '8'],
 ['1', '23'],
 ['2', '48'],
 ['3', '83'],
 ['4', '128'],
 ['5', '183'],
 ['6', '248'],
 ['7', '323'],
 ['8', '408'],
 ['9', '503'],
 ['10', '608'],
 ['11', '723'],
 ['12', '848'],
 ['13', '983'],
 ['14', '1128'],
 ['15', '1283'],
 ['16', '1448'],
 ['17', '1623'],
 ['18', '1808'],
 ['19', '2003'],
 ['20', '2208'],
 ['21', '2423'],
 ['22', '2648'],
 ['23', '2883'],
 ['24', '3128'],
 ['25', '3383'],
 ['26', '3648'],
 ['27', '3923'],
 ['28', '4208'],
 ['29', '4503'],
 ['30', '4808'],
 ['31', '5123'],
 ['32', '5448'],
 ['33', '5783'],
 ['34', '6128'],
 ['35', '6483'],
 ['36', '6848'],
 ['37', '7223'],
 ['38', '7608'],
 ['39', '8003'],
 ['40', '8408'],
 ['41', '8823'],
 ['42', '9248'],
 ['43', '9683'],
 ['44', '10128'],
 ['45', '10583'],
 ['46', '11048'],
 ['47', '11523'],
 ['48', '12008'],
 ['49', '12503'],
 ['50', '13008'],
 ['51', '13523'],
 ['52', '14048'],
 ['53', '14583'],
 ['54', '15128'],
 ['55', '15683'],
 ['56', '16248'],
 ['57', '16823'],
 ['58', '17408'],
 ['59', '18

In [62]:
A = []
B = []
for j in β:
    A.append(float(j[0]))
    B.append(float(j[1]))

In [63]:
v1 = np.array(A)
v2 = np.array(B)

In [64]:
v1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

# 

Resulta que hay una manera más fácil, de más alto nivel y más rápida de hacer esto:

In [1]:
map(float, palabras)

NameError: name 'palabras' is not defined

Eso literalmente mapea la función float sobre la lista palabras.

Combinando todo, podemos escribir:

In [25]:
entrada = open("datos.dat", "r")

for linea in entrada:
    datos = map(float, linea.split())

Y ya dentro del bucle podemos manipular los datos como queramos.

### **Ejercicio:** 

Escribe un programa que lea el archivo `datos.dat` y guarde en una arreglo de `numpy` los datos de la primera columna y en otro diferente los datos de la segunda columna.

### SALIDA

Como ya hemos visto en el *interprete de comandos python*, en *ipython* o *Jupyter*, para mandar un resultado a la salida simplemente hay que definirlo y después escribirlo y presionar enter.

In [ ]:
a = 17.3
a

In [ ]:
b = "hola"
b

Adicionalmente se puede utilizar el comando `print()`

In [ ]:
print("imprimiendo datos", a, b)

### Escribir archivos

Para mandar las salida del programa a un archivo (escribir), también se usa el comando `open()`; pero para este caso hay que generar un *`buffer`* de escritura, especificando se sera de escritura:

`open("archoDeEscritura.dat",`**`"w"`**`)`

Para hacer eso, necesitamos poder abrir un archivo para escribirse:

In [ ]:
salida = open("resultados.dat", "w")  # Esto es un buffer de salida

La parte más complicada viene al momento de escribir en el archivo. Para hacerlo, ocupamos la función:

`salida.write()`

Sin embargo, esta función puede escribir solamente cadenas. Por lo tanto, si queremos escribir números contenidos en variables, es necesario convertirlos primero a la forma de cadena.

Una manera de hacer eso es con la función str(), y concatenar (juntar) distintas cadenas con +:



In [ ]:
a = 3
s = "El valor de a es " + str(a)

print(s)

Sin embargo, para largas secuencias de datos eso se vuelve latoso.

La manera más elegante de hacerlo es con la sustitución de variables en cadenas . En una cadena ponemos una secuencia especial de caracteres, empezando por `%`, que indica que se sustituirá el valor de una variable:

In [ ]:
a = 3
s = "El valor de a es %d" % a

b = 3.5; c = 10.1
s = "b = %g; c = %g" % (b, c)

El carácter después del `%` indica el tipo de variable que incluir en la cadena: 

- **`d`** corresponde a un _**entero**_, 


- **`g`**  o **`f`**  a un _**flotante**_ y 


- **`s`**  a _**otra cadena**_.


Finalmente ahora podemos imprimir en el archivo, por ejemplo:

In [ ]:
salida.write(" %g\t %g" % (a,b) )

Aquí, **`\t`** representa un tabulador, y **`\n`** una nueva línea.

#### Ejemplo

In [70]:
def fibonacci(n):
    
    output = []
    
    f1,f2 = 1,1

    while f2 < n:
        output.append(f2)        
        f1,f2 = f2,f1+f2
    
    return output


In [71]:
F100 = fibonacci(100)

In [72]:
tubo = open("resutados.dat","w")

In [75]:
for i in F100:
    tubo.write("%d \n" % i)

tubo.close()

In [ ]:
fibo = fibonacci(100)

outputBuff = open("fibonacci.dat", "w")

for n in fibo:
    outputBuff.write("%d \n" % n)
#     outputBuff.write("%f \n" % n)

outputBuff.close()

In [ ]:
fibo2 = fibonacci(1000)

with open("fibonacci2.dat", 'a') as out:
    for n in fibo2:
        out.write(str(n) + '\n')

### **Ejercicio:** 

Usando los arreglos de `numpy` del ejercicio anterior, que contienen los datos recolectados del archivo `datos.dat`; escribe un programa que escriba **dos archivos de texto diferentes**, que guarden los datos de cada arreglo.

## Scripts de Python.

Una vez que las secuencias de comandos se complican, podría pasar que queramos repetir la misma secuencia varias veces o bien reusar algunas secuencias de comandos, sin embargo esto significaría reescribir todo nuevamente en el interprete de comandos, o estar editando y volviendo a correr las celdas en *Jupyter*.

Entonces sería conveniente poder guardar bloques de instrucciones completos y correrlos de una sola vez.
Esto es posible realizando un *programa*, o _**script**_. 

Esto consiste en un **archivo de texto**, cuyo nombre termina en **.py**, en el cual se escribe y guarda la secuencia de comandos.

Por ejemplo, consideremos el siguiente código: 

In [ ]:
from fractions import Fraction

a = Fraction(3, 5)
b = Fraction(1)
c = a + b
d = Fraction(4, 6)
d 
e = a + d
print(a,b,c,d,e)

podemos escribirlo en un editor de textos y salvarlo como un archivo cuad.py. Y así entonces podemos correr el código desde **ipython** o _**Jupyter Notebook**_, de la siguiente manera:

In [ ]:
run cuad.py

**Nota:** si no estamos en el mismo directorio donde se guardo el archivo script.py, habrá que especificar la ruta relativa o absoluta según sea el caso.

Alternativamente, podemos tratar el script como un *programa* en sí, y **ejecutarlo desde la consola**:

**`$>`**`python cuad.py`

Aunque no hay una forma rígida de programar, para escribir un buen script (programa) se puede seguir la siguiente estructura:

- `Comentarios generales del programa`


- `Importar bibliotecas (librerías o módulos)`


- `Definir funciones`


- `Definir variables globales`


- `Comandos de entrada por parte del usuario (si es necesario)`


- `Estructuras de control y/o cálculos`


- `Comandos de salida (si es necesario)`

Finalmente, es posible exportar los _**Cuadernos de Jupyter**_, como **scripts**, desde el menu *File*.
Intentalo ...